[project]
name = "autoingest"
requires-python = "==3.13.*"
version = "0.1.0"
dependencies = [
    "dagster",
    "dagster-dg-cli",
    "dagster-postgres",
    "dagster-webserver",
    "dagster-celery[redis]",
    "sqlalchemy",
    "psycopg2-binary",
    "redis",
    "ffmpeg-python",
    "python-magic",
    "pytz",
    "requests",
    "tenacity",
    "xmltodict",
    "Pillow",
    "setuptools.backends",
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "dagster-dg-cli",
    "pytest",
]

[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.backends._legacy:_Backend"

[tool.dagster]
module_name = "autoingest.definitions"

[tool.setuptools.packages.find]
include = ["autoingest*"]
